# nums_list = list(reversed(input().split()))
# nums_list.sort(reverse=True)
# print("".join(nums_list))
nums_list = list(reversed(input().split()))
nums_list.sort(reverse=True)
print("".join(nums_list))
